### ISSUE TITLE
Add support for additional Labels

### ISSUE THREAD

**Issue by arohter** [lensesio/lenses-helm-charts#4]
We have audit Labeling requirements for our cluster, and enforcement goes beyond just the Deployment (https://github.com/lensesio/lenses-helm-charts/blob/release/4.1/charts/lenses/values.yaml#L14)
to Services and Ingresses as well,

so feature request to add optional `labels: {}` config to other resources as well:
https://github.com/lensesio/lenses-helm-charts/blob/release/4.1/charts/lenses/values.yaml#L67
https://github.com/lensesio/lenses-helm-charts/blob/release/4.1/charts/lenses/values.yaml#L96

**Comment by mpeters0n** [comment]
#5

**Comment by arohter** [comment]
🚀  on the quick turnaround !
