### ISSUE TITLE
Helm installation is failing

### ISSUE THREAD

**Issue by Patanouk** [lensesio/lenses-helm-charts#9]
Hello,

We tried to install the helm chart, but the deployment is referencing a non-existent secret key (https://github.com/lensesio/lenses-helm-charts/blob/release/4.3/charts/lenses/templates/deployment.yaml#L64), hence the volume mount is failing

The secret key was removed in commit f096caf137d19308c7165f610680d183036974dc

I don't have time now, but I can submit a PR over the weekend if there's any interest

**Comment by Patanouk** [comment]
I opened https://github.com/lensesio/lenses-helm-charts/pull/10

**Comment by georgeyord** [comment]
Fix merged on version `4.3.13`, thanks again for the contribution! 🚀

**Comment by Patanouk** [comment]
Cool, thx for the update
